--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jhelom/WorldBackup-plugin-pocketmine
submodule: true
branches:
- master
projects:
  WorldBackup:
    path: ""
    icon: "assets/icon.png"
...
